trigger:
  branches:
    exclude:
      - master

pool:
  vmImage: windows-latest

steps:
  # https://marketplace.visualstudio.com/items?itemName=Sam-Cogan.ARMTTKExtension
  - task: RunARMTTKTests@1
    inputs:
      templatelocation: $(System.DefaultWorkingDirectory)\templates
      resultLocation: $(System.DefaultWorkingDirectory)\results
      allTemplatesMain: true
      cliOutputResults: true
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
    condition: always()